name: cats-git-config-project

protocol: https

clowder:
  cats:
    - name: JrGoodle/mu
      branch: knead
      git:
        config:
          alias.something: "!echo 'Run git something alias installed via clowder'; touch something"
    - name: JrGoodle/duke
      branch: purr
  black-cats:
    path: black-cats
    projects:
      - JrGoodle/kit
      - JrGoodle/kishka
      - JrGoodle/june
      - JrGoodle/sasha
